apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: NAMESPACE
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: odoo
  POSTGRES_PASSWORD: PG_RANDOM_PASSWORD