apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: postgresql-pv-NAMESPACE
  labels:
    type: local # Sets PV's type to local
spec:
  storageClassName: NAMESPACE
  capacity:
    storage: STORAGE_CAPACITY # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/NAMESPACE" # Sets the volume's path