apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: postgresql-pvc
  namespace: NAMESPACE
spec:
  storageClassName: NAMESPACE
  accessModes:
    - ReadWriteMany # Sets read and write access
  resources:
    requests:
      storage: STORAGE_CAPACITY # Sets volume size